import { StyleSheet } from 'react-native';
import { colors } from '@/theme/colors';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.oceanDeep },
  header: { paddingHorizontal: 20, paddingTop: 56, paddingBottom: 8 },
  title: { color: colors.white, fontSize: 20, fontWeight: '600' },
  sub: { color: colors.textMuted, fontSize: 12, marginTop: 2 },
  mapContainer: { height: 220, marginHorizontal: 16, marginTop: 8, borderRadius: 16, overflow: 'hidden', borderWidth: 1, borderColor: colors.cardBorder },
  map: { flex: 1 },
  addMapBtn: { position: 'absolute', bottom: 10, right: 10, backgroundColor: colors.accent, borderRadius: 20, paddingHorizontal: 14, paddingVertical: 7 },
  addMapBtnText: { color: colors.white, fontSize: 13, fontWeight: '600' },
  callout: { position: 'absolute', top: 10, left: 10, right: 10, backgroundColor: colors.oceanMid, borderRadius: 10, padding: 10, borderWidth: 1, borderColor: 'rgba(255,255,255,0.2)' },
  calloutHint: { color: colors.oceanLight, fontSize: 11, marginTop: 4 },  calloutTitle: { color: colors.white, fontSize: 13, fontWeight: '600', marginBottom: 2 },
  calloutSub: { color: colors.textMuted, fontSize: 11 },
  calloutDist: { color: colors.oceanLight, fontSize: 11, marginTop: 2 },
  calloutRating: { color: colors.accent, fontSize: 11, marginTop: 4 },
  searchWrap: { flexDirection: 'row', alignItems: 'center', backgroundColor: colors.cardBg, borderWidth: 1, borderColor: colors.cardBorder, borderRadius: 12, marginHorizontal: 16, marginTop: 10, marginBottom: 8, paddingHorizontal: 14, paddingVertical: 10 },
  searchInput: { flex: 1, color: colors.white, fontSize: 13, marginLeft: 8 },
  favBtn: { padding: 4, borderRadius: 8 },
  favBtnActive: { backgroundColor: 'rgba(244,168,38,0.2)' },
  chip: { backgroundColor: colors.cardBg, borderWidth: 1, borderColor: colors.cardBorder, borderRadius: 20, paddingHorizontal: 12, paddingVertical: 5 },
  chipActive: { backgroundColor: colors.accent, borderColor: colors.accent },
  chipSpeciesActive: { backgroundColor: colors.oceanLight, borderColor: colors.oceanLight },
  chipText: { color: colors.textMuted, fontSize: 12 },
  pointCard: { backgroundColor: colors.cardBg, borderWidth: 1, borderColor: colors.cardBorder, borderRadius: 14, padding: 14, marginBottom: 10 },
  pointCardActive: { borderColor: colors.accent, backgroundColor: 'rgba(244,168,38,0.08)' },
  hotBadge: { backgroundColor: 'rgba(244,168,38,0.2)', borderWidth: 1, borderColor: colors.accent, borderRadius: 6, paddingHorizontal: 8, paddingVertical: 3 },
  typeTag: { backgroundColor: 'rgba(42,159,196,0.2)', borderWidth: 1, borderColor: colors.oceanLight, borderRadius: 6, paddingHorizontal: 8, paddingVertical: 3 },
  tag: { backgroundColor: 'rgba(255,255,255,0.08)', borderRadius: 6, paddingHorizontal: 8, paddingVertical: 3 },
  tagText: { color: colors.textMuted, fontSize: 11 },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.7)', justifyContent: 'flex-end' },
  modalContent: { backgroundColor: colors.oceanMid, borderTopLeftRadius: 24, borderTopRightRadius: 24, padding: 20, maxHeight: '90%' },
  modalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 16 },
  modalTitle: { color: colors.white, fontSize: 16, fontWeight: '600', flex: 1 },
  detailRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: 'rgba(255,255,255,0.08)' },
  detailLabel: { color: colors.textMuted, fontSize: 13 },
  detailValue: { color: colors.white, fontSize: 13, fontWeight: '500' },
  deleteBtn: { backgroundColor: 'rgba(224,92,26,0.2)', borderWidth: 1, borderColor: colors.accent2, borderRadius: 12, padding: 14, alignItems: 'center', marginTop: 16 },
  deleteBtnText: { color: colors.accent2, fontSize: 14, fontWeight: '600' },
  input: { backgroundColor: colors.cardBg, borderWidth: 1, borderColor: colors.cardBorder, borderRadius: 12, padding: 14, color: colors.white, fontSize: 14, marginBottom: 10 },
  inputLabel: { color: colors.textMuted, fontSize: 12, marginBottom: 8 },
  mapTapBtn: { backgroundColor: colors.cardBg, borderWidth: 1, borderColor: 'rgba(255,255,255,0.2)', borderRadius: 12, padding: 14, alignItems: 'center', marginBottom: 8 },
  mapTapBtnActive: { borderColor: colors.accent, backgroundColor: 'rgba(244,168,38,0.1)' },
  myLocBtn: { backgroundColor: 'rgba(42,159,196,0.2)', borderWidth: 1, borderColor: colors.oceanLight, borderRadius: 12, padding: 12, alignItems: 'center', marginBottom: 8 },
  submitBtn: { backgroundColor: colors.accent, borderRadius: 12, paddingVertical: 14, alignItems: 'center', marginTop: 4 },
  submitBtnText: { color: colors.white, fontSize: 15, fontWeight: '600' },
});
