import { StyleSheet } from 'react-native';
import { colors } from '@/theme/colors';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.oceanDeep },
  header: { paddingHorizontal: 20, paddingTop: 56, paddingBottom: 8 },
  title: { color: colors.white, fontSize: 20, fontWeight: '600' },
  sub: { color: colors.textMuted, fontSize: 12, marginTop: 2 },
  tabRow: { flexDirection: 'row', marginHorizontal: 16, marginBottom: 12, backgroundColor: colors.cardBg, borderRadius: 12, padding: 4 },
  tabBtn: { flex: 1, paddingVertical: 8, alignItems: 'center', borderRadius: 10 },
  tabBtnActive: { backgroundColor: colors.accent },
  tabText: { color: colors.textMuted, fontSize: 13, fontWeight: '500' },
  tabTextActive: { color: colors.white },
  aiSection: { marginHorizontal: 16, marginBottom: 10, backgroundColor: 'rgba(42,159,196,0.15)', borderWidth: 1, borderColor: colors.oceanLight, borderRadius: 16, padding: 14 },
  aiTitle: { color: colors.white, fontSize: 14, fontWeight: '600', marginBottom: 4 },
  aiSub: { color: colors.textMuted, fontSize: 11, lineHeight: 16, marginBottom: 12 },
  btnRow: { flexDirection: 'row' },
  cameraBtn: { flex: 1, backgroundColor: colors.accent, borderRadius: 10, paddingVertical: 10, alignItems: 'center', marginRight: 8 },
  cameraBtnText: { color: colors.white, fontSize: 13, fontWeight: '600' },
  galleryBtn: { flex: 1, backgroundColor: 'rgba(255,255,255,0.1)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.2)', borderRadius: 10, paddingVertical: 10, alignItems: 'center' },
  galleryBtnText: { color: colors.white, fontSize: 13, fontWeight: '600' },
  searchWrap: { flexDirection: 'row', alignItems: 'center', backgroundColor: colors.cardBg, borderWidth: 1, borderColor: colors.cardBorder, borderRadius: 12, marginHorizontal: 16, marginBottom: 8, paddingHorizontal: 14, paddingVertical: 10 },
  searchInput: { flex: 1, color: colors.white, fontSize: 13, marginLeft: 8 },
  centerWrap: { flex: 1, alignItems: 'center', justifyContent: 'center', paddingVertical: 40 },
  resultCard: { flexDirection: 'row', alignItems: 'center', backgroundColor: colors.cardBg, borderWidth: 1, borderColor: colors.cardBorder, borderRadius: 14, padding: 12, marginBottom: 10 },
  thumbnail: { width: 60, height: 60, borderRadius: 10 },
  taxonTag: { backgroundColor: 'rgba(42,159,196,0.2)', borderWidth: 1, borderColor: colors.oceanLight, borderRadius: 6, paddingHorizontal: 8, paddingVertical: 3 },
  taxonText: { color: colors.oceanLight, fontSize: 11 },
  catTitle: { color: colors.white, fontSize: 14, fontWeight: '600', marginBottom: 10 },
  recommendChip: { backgroundColor: colors.cardBg, borderWidth: 1, borderColor: 'rgba(255,255,255,0.15)', borderRadius: 20, paddingHorizontal: 14, paddingVertical: 8, marginRight: 8 },
  recommendChipText: { color: colors.white, fontSize: 13 },
  tipBox: { backgroundColor: 'rgba(42,159,196,0.1)', borderWidth: 1, borderColor: 'rgba(42,159,196,0.3)', borderRadius: 12, padding: 14, marginTop: 8 },
  tipText: { color: colors.textMuted, fontSize: 12, lineHeight: 20, textAlign: 'center' },
  // 내 도감 그리드 스타일
  myFishGrid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between' },
  myFishGridCard: { width: '48%', backgroundColor: colors.cardBg, borderWidth: 1, borderColor: colors.cardBorder, borderRadius: 14, marginBottom: 12, overflow: 'hidden' },
  myFishGridPhoto: { width: '100%', height: 110, borderRadius: 0 },
  myFishGridPhotoPlaceholder: { width: '100%', height: 110, backgroundColor: 'rgba(255,255,255,0.05)', alignItems: 'center', justifyContent: 'center' },
  myFishGridInfo: { padding: 10 },
  myFishGridName: { color: colors.white, fontSize: 14, fontWeight: '600' },
  myFishGridSize: { color: colors.accent, fontSize: 12, marginTop: 3 },
  myFishGridLocation: { color: colors.textMuted, fontSize: 11, marginTop: 2 },
  myFishGridCount: { color: colors.oceanLight, fontSize: 11, marginTop: 2 },
  editBadge: { position: 'absolute', top: 8, right: 8, backgroundColor: 'rgba(0,0,0,0.5)', borderRadius: 12, width: 24, height: 24, alignItems: 'center', justifyContent: 'center' },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.7)', justifyContent: 'flex-end' },
  modalContent: { backgroundColor: colors.oceanMid, borderTopLeftRadius: 24, borderTopRightRadius: 24, padding: 20, maxHeight: '90%' },
  modalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 16 },
  modalTitle: { color: colors.white, fontSize: 18, fontWeight: '600', flex: 1 },
  previewImage: { width: '100%', height: 150, borderRadius: 12, marginBottom: 12 },
  detailPhoto: { width: '100%', height: 220, borderRadius: 12 },
  registerBtn: { backgroundColor: colors.oceanLight, borderRadius: 12, paddingVertical: 14, alignItems: 'center', marginTop: 12 },
  registerBtnText: { color: colors.white, fontSize: 15, fontWeight: '600' },
  closeBtn: { backgroundColor: colors.accent, borderRadius: 12, paddingVertical: 14, alignItems: 'center', marginTop: 4 },
  closeBtnText: { color: colors.white, fontSize: 15, fontWeight: '600' },
  infoSection: { backgroundColor: 'rgba(255,255,255,0.05)', borderRadius: 12, padding: 14, marginBottom: 12 },
  infoSectionTitle: { color: colors.white, fontSize: 14, fontWeight: '600', marginBottom: 8 },
  detailRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 8, borderBottomWidth: 1, borderBottomColor: 'rgba(255,255,255,0.08)' },
  detailLabel: { color: colors.textMuted, fontSize: 12 },
  detailValue: { color: colors.white, fontSize: 12, fontWeight: '500', maxWidth: '60%', textAlign: 'right' },
  input: { backgroundColor: colors.cardBg, borderWidth: 1, borderColor: colors.cardBorder, borderRadius: 12, padding: 14, color: colors.white, fontSize: 14, marginBottom: 10 },
  inputLabel: { color: colors.textMuted, fontSize: 12, marginBottom: 6 },
  hintText: { color: 'rgba(255,255,255,0.45)', fontSize: 11, textAlign: 'center', marginTop: 10 },
  errorText: { color: colors.accent2, fontSize: 13, textAlign: 'center' },
});